services:
  ga-matching-api:
    image: patrick5471/ga-matching-api:latest
    container_name: ga-matching-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ga-network

networks:
  ga-network:
    driver: bridge
